- name: LOGO_THUMBNAIL
  value: '/brand-assets/textyomni_logo.png'
- name: LOGO
  value: '/brand-assets/textyomni_logo.png'
- name: INSTALLATION_NAME
  value: 'TextyOmni'
- name: BRAND_URL
  value: 'https://usg.textyomni.com'
- name: WIDGET_BRAND_URL
  value: 'https://usg.textyomni.com'
- name: TERMS_URL
  value: 'https://www.textyomni.com/tc'
- name: PRIVACY_URL
  value: 'https://www.textyomni.com/privacy'
- name: DISPLAY_MANIFEST
  value: true
- name: MAILER_INBOUND_EMAIL_DOMAIN
  value: 'textyomni.com'
- name: MAILER_SUPPORT_EMAIL
  value: 'support@textyomni.com'
- name: CREATE_NEW_ACCOUNT_FROM_DASHBOARD
  value: true
- name: BRAND_NAME
  value: 'TextyOmni'
- name: 'INSTALLATION_EVENTS_WEBHOOK_URL'
  value: 
